# Generated by Django 4.2.16 on 2024-09-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipopermisos', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permisos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=50)),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_tipo_permisos', models.ForeignKey(db_column='id_tipo_permisos', on_delete=django.db.models.deletion.CASCADE, to='tipopermisos.tipo_permiso')),
            ],
        ),
    ]
