# Generated by Django 4.2.16 on 2024-09-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salarios', '0001_initial'),
        ('empleados', '0005_alter_empleado_numero_inss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id_beneficios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_beneficio', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarios.salario')),
            ],
        ),
    ]
