# Generated by Django 4.2.16 on 2024-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_numero_inss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='numero_inss',
            field=models.CharField(default=12345678912, max_length=11),
        ),
    ]
