# Generated by Django 4.2.16 on 2024-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallepermiso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_permiso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalle_permiso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
