# Generated by Django 4.2.16 on 2024-09-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('tipocontratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contratos', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_contrato', models.CharField(max_length=8)),
                ('id_empleado', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_tipo_contratos', models.ForeignKey(db_column='id_tipo_contratos', on_delete=django.db.models.deletion.CASCADE, to='tipocontratos.tipo_contrato')),
            ],
        ),
    ]
