# Generated by Django 4.2.16 on 2024-09-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_conclusion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
