# Generated by Django 4.2.16 on 2024-09-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0001_initial'),
        ('contratos', '0003_alter_contrato_fecha_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='id_jornada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jornadas.jornada'),
        ),
    ]
