# Generated by Django 4.2.16 on 2024-09-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipodocumentos', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentos_personales',
            fields=[
                ('id_documentos_personales', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_archivo', models.CharField(max_length=100)),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_tipo_documentos', models.ForeignKey(db_column='id_tipo_documentos', on_delete=django.db.models.deletion.CASCADE, to='tipodocumentos.tipo_documento')),
            ],
        ),
    ]
