# Generated by Django 4.2.16 on 2024-09-17 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_personales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_personales',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
