# Generated by Django 4.2.16 on 2024-09-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('id_deducciones', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarios.salario')),
            ],
        ),
    ]
