# Generated by Django 4.2.16 on 2024-09-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_contratos', models.ForeignKey(db_column='id_contratos', on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
            ],
        ),
    ]
